apiVersion: v1
kind: ReplicationController
metadata:
  name: netty
  labels:
    name: netty
    app: dcs
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: netty
    spec:
      containers:
        - name: netty
          image: amankataria/centos:latest
          ports:
            - containerPort: 9999
              name: http
              protocol: TCP
          command: ["sh"]
          args: ["/usrdata/apps/appserver/netty/bin/start-tej-netty-server-kubernetes.sh"]
