apiVersion: v1
kind: Service
metadata:
  name: netty
  labels:
    name: netty
    app: dcs
spec:
  type: LoadBalancer
  selector:
    name: netty
    app: dcs
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
